### ISSUE TITLE
Beeping when trying to open the window

### ISSUE THREAD

**Issue by DaQueenJodi** [nkrapivin/KittyNXBuilder#10]
I have no idea whether or not this is my fault, but sometimes when I minimize the app and try to open it again while its building, itll just beep at me (the windows 10 default "you did something bad" sound) and doesn't let me open it. This happens when Alt Tabbing into it and when clicking on it in the system tray. This is random and if I spam click it, it'll eventually let me open it

using version 1.6 (latest release)  and runtime 2.3.7.476 NuBeta 

I have no idea how to debug this kind of stuff on windows, so if more info is needed, let me know

**Comment by nkrapivin** [comment]
Yeah because while it's building the app locks up, waiting for GMAssetCompiler to quit. It does try to process UI events but it only works 50% of the time. Windows thinks the app is "frozen" while in reality it is not.
