### ISSUE TITLE
Value cannot be null error

### ISSUE THREAD

**Issue by nexuswk** [nkrapivin/KittyNXBuilder#17]
Trying to compile an older Pizza Tower build, and I'm getting a weird null error.
Does anyone possibly know why?
![image_2023-07-01_222253418](https://github.com/nkrapivin/KittyNXBuilder/assets/98617712/30a4b480-5d5e-46ca-86ee-8740eeac5c0d)

**Comment by nkrapivin** [comment]
Please don't.
You're the... sixth? person? who comes to me asking about That One Pizza Tower Project File.
It's inherently broken and needs fixing.
